#!/bin/sh
# 
#
case "$1" in
start)
	if [ -x /usr/local/sbin/rpc.statd ]; then
		start-stop-daemon --start --exec /usr/local/sbin/rpcbind
		start-stop-daemon --start --exec /usr/local/sbin/rpc.statd
		mount -a -t nfs
		echo "Starting nfs client utilities."
	else
		echo "rpc.statd is missing.  You need to install nfs-utils."
	fi
;;

stop)
	umount -a -t nfs
	start-stop-daemon --stop --exec /usr/local/sbin/rpc.statd
;;

restart)
  	$0 stop
  	$0 start
;;

status)
	if ps | awk '{print $3}' | grep -e "/usr/local/sbin/rpc.statd" >/dev/null; then
		echo "NFS-client is running."
		exit 0
	else
		echo "NFS-client is not running."
		exit 1
	fi
;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
