#!/bin/sh
# RC Script for Tiny Core Linux
# (c) Robert Shingledecker 2004-2012

# Mount /proc.
[ -f /proc/cmdline ] || /bin/mount /proc

# Remount rootfs rw.
/bin/mount -o remount,rw /

# Mount system devices from /etc/fstab.
/bin/mount -a

/usr/local/bin/cgroupfs-mount

# don't want/need console messages
echo 0 > /proc/sys/kernel/printk

/etc/init.d/tc-config > /dev/null

/usr/local/sbin/rpcbind

try_mount() {
  local exp="$(awk 'BEGIN { FS="="; RS=" " } $1 == "nfsexport" { print $2 }' < /proc/cmdline)"
  if [ -n "${exp}" ]; then
    mount -t nfs "192.168.64.1:${exp}" /src 2>/dev/null
  else
    # no cmdline for mount, so just don't mount anything.
    true
  fi
}

count=0
while [ 1 ]; do
  if try_mount; then
    break
  else
    if [ $count -lt 2 ]; then
      :
    elif [ $count -eq 2 ]; then
      >&2 echo -n "waiting for network..."
    elif [ $count -eq 15 ]; then
      >&2 echo -en "\n\x1b[31mnetwork didn't come up in time: aborting.\x1b[0m"
      halt -f
    else
      >&2 echo -n "."
    fi
    count=$(expr $count + 1)
    sleep 0.5
  fi
done

